### ISSUE TITLE
타일 이미지 서버 연동

### ISSUE THREAD

**Issue by grohong** [TileImageTeamiOS/THTiledImageView#4]
- [ ] 있는 이미지를 다운로드 후 (비동기로) 보여주는 기능
- [ ] 앱이 백그라운드인 상태에서 이미지 다운로드하는 기능

**Comment by hcn1519** [comment]
이미지 서버에 줌 레벨 마다 Request를 날려서 이미지를 캐싱하는 형태로 구현
- 이미지 서버에 과도한 Request가 날아갈 수 있기 때문에 테스트 필요

**Comment by hcn1519** [comment]
이미지 caching은 [king fisher](https://github.com/onevcat/Kingfisher) 코드를 참고하면서 구현

**Comment by hcn1519** [comment]
We resolve this issue from Version [0.3.0](https://github.com/TileImageTeamiOS/THTiledImageView/tree/0.3.0).
